name: dotNet Templates

on:
  push:
    branches: [main]

jobs:
  build:

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET 
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'
        dotnet-quality: 'ga'

    - name: Build
      run: dotnet pack --nologo --configuration:"PackRelease" --use-current-runtime

    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push ./bin/**/*.nupkg -k ${NUGET_ACCESS_TOKEN} --source "nuget.org" --skip-duplicate --no-symbols 
      env:
        NUGET_ACCESS_TOKEN: ${{ secrets.NUGET_ACCESS_TOKEN }}
